"""Added tables

Revision ID: ca787e744366
Revises: d586e2477330
Create Date: 2026-06-26 18:04:18.398988

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca787e744366"
down_revision: Union[str, None] = "d586e2477330"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_words", sa.Column("source", sa.String(), server_default="", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_words", "source")
    # ### end Alembic commands ###
