"""Added tables

Revision ID: d586e2477330
Revises: e696d2d0b612
Create Date: 2026-06-02 16:42:52.777779

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d586e2477330"
down_revision: Union[str, None] = "e696d2d0b612"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("languages", sa.Column("display", sa.String(), server_default="", nullable=False))
    op.alter_column("languages", "name", new_column_name="value")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("languages", "display")
    op.alter_column("languages", "value", new_column_name="name")
    # ### end Alembic commands ###
