"""Added tables

Revision ID: ef3ce54c13dc
Revises: da0b8e6d301c
Create Date: 2026-02-09 17:15:23.567508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef3ce54c13dc'
down_revision: Union[str, None] = 'da0b8e6d301c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks_cron')
    op.drop_table('tasks_periodic')
    op.add_column('user_sessions', sa.Column('subject', sa.String(), nullable=True))
    op.drop_constraint(op.f('user_sessions_query_id_key'), 'user_sessions', type_='unique')
    op.drop_column('user_sessions', 'query_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_sessions', sa.Column('query_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('user_sessions_query_id_key'), 'user_sessions', ['query_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_sessions', 'subject')
    op.create_table('tasks_periodic',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('run_every', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_periodic_pkey'))
    )
    op.create_table('tasks_cron',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('minute', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hour', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('day_of_week', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('day_of_month', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('month_of_year', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tasks_cron_pkey'))
    )
    # ### end Alembic commands ###
