# Generated by Django 5.2.3 on 2025-07-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="examples",
        ),
        migrations.RemoveField(
            model_name="word",
            name="synonyms",
        ),
    ]
